services:

  mysqldb:
    build: ./mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    ports:
      - 63306:3306

  webapp:
    build: .
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: dashboard
      DB_USER: mddashboard
      DB_PASSWORD: geheim
    ports:
      - 9280:9080
